variable "vpn_ip_address" {}
variable "vpn_bgp_asn" {}
variable "zone" {}
variable "preshared_key" {}
variable "name" {}
variable "route_table_id" {}
variable "vpc_id" {}
variable "destination_cidr_block" {}
variable "amazon_side_asn" {}
